
#########
# Users #
#########

# List all users
GET http://localhost:5000/v1/api/users HTTP/1.1

# Create User
POST http://localhost:5000/v1/api/users HTTP/1.1

{
    "name": "praveen"
}

# Delete all users
DELETE http://localhost:5000/v1/api/users HTTP/1.1

# Get User By ID
GET http://localhost:5000/v1/api/users/4 HTTP/1.1

# Update User
PUT http://localhost:5000/v1/api/users/4 HTTP/1.1

{
    "name": "praveen2"
}

# Delete user by ID
DELETE http://localhost:5000/v1/api/users/2 HTTP/1.1

# Get user's feeds
GET http://localhost:5000/v1/api/users/2/feeds HTTP/1.1

# Create a feed for new
POST http://localhost:5000/v1/api/users/{userID}/feeds HTTP/1.1

# Delete all feeds of user
DELETE http://localhost:5000/v1/api/users/{userID}/feeds HTTP/1.1

#########
# Feeds #
#########

# List all feeds (not needed)
GET http://localhost:5000/v1/api/feeds HTTP/1.1

# Create feed (not needed)
POST http://localhost:5000/v1/api/feeds HTTP/1.1

{
    "name": "testfeed"
}

# Delete all feeds (not needed)
DELETE http://localhost:5000/v1/api/feeds HTTP/1.1

# Get feed By ID
GET http://localhost:5000/v1/api/feeds/1 HTTP/1.1

# Update feed
PUT http://localhost:5000/v1/api/feeds/{feedID} HTTP/1.1

# Delete feed by ID
DELETE http://localhost:5000/v1/api/feeds/{feedID} HTTP/1.1


# Create Playlist
POST http://localhost:5000/v2/api/feeds/1/playlists

{
    "playOn": 1551810600000,
    "items": [
        {
            "assetId": "hello-world",
            "startTime": 12
        },
        {
            "assetId": "hello-world",
            "startTime": 12
        }
    ],
    "type": "normal"
}

# Find playlist by ID
GET http://localhost:5000/v2/api/feeds/1/playlists/1


GET http://localhost:5000/v2/api/feeds/1/playlists/date/1551810600000

# Update
PUT http://localhost:5000/v2/api/feeds/1/playlists/1

{
    "playOn": 1551810600000,
    "items": [
        {
            "assetId": "hello-world-2",
            "startTime": 14
        }
    ],
    "type": "normal"
}


POST http://localhost:5000/v1/api/auth HTTP/1.1

{
    "accessToken": "allowme",
    "email": "praveen@amagi.com",
    "token":"hello-world",
    "accountCode": "XYZ",
    "feedCode": "ABC"
}

# Get Medias List
GET http://localhost:5000/v2/api/feeds/1/medias?limit=10&search=d&category=media&category=graphics